/* soapServer.cpp
   Generated by gSOAP 2.7.9a from getStates.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.9a 2012-10-23 03:16:41 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getGrowBoxInfo"))
		return soap_serve_ns__getGrowBoxInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:performAction"))
		return soap_serve_ns__performAction(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getGrowBoxInfo(struct soap *soap)
{	struct ns__getGrowBoxInfo soap_tmp_ns__getGrowBoxInfo;
	GrowBoxInfo Result;
	Result.soap_default(soap);
	soap_default_ns__getGrowBoxInfo(soap, &soap_tmp_ns__getGrowBoxInfo);
	soap->encodingStyle = "";
	if (!soap_get_ns__getGrowBoxInfo(soap, &soap_tmp_ns__getGrowBoxInfo, "ns:getGrowBoxInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getGrowBoxInfo(soap, &Result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	Result.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || Result.soap_put(soap, "GrowBoxInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || Result.soap_put(soap, "GrowBoxInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__performAction(struct soap *soap)
{	struct ns__performAction soap_tmp_ns__performAction;
	struct ns__performActionResponse soap_tmp_ns__performActionResponse;
	soap_default_ns__performActionResponse(soap, &soap_tmp_ns__performActionResponse);
	soap_default_ns__performAction(soap, &soap_tmp_ns__performAction);
	soap->encodingStyle = "";
	if (!soap_get_ns__performAction(soap, &soap_tmp_ns__performAction, "ns:performAction", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__performAction(soap, soap_tmp_ns__performAction.actionCode, soap_tmp_ns__performActionResponse.return_Code);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__performActionResponse(soap, &soap_tmp_ns__performActionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__performActionResponse(soap, &soap_tmp_ns__performActionResponse, "ns:performActionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__performActionResponse(soap, &soap_tmp_ns__performActionResponse, "ns:performActionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
